services:
  buildapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    command: echo "I'm just a build helper"
  init:
    build:
      context: .
      dockerfile: Dockerfile.init
    volumes:
      - ./data:/app/data
      - ./scripts/create_data_file.py:/app/scripts/create_data_file.py
    working_dir: /app
    command: python ./scripts/create_data_file.py
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3307:3306"
    networks:
      - mynet
  migrations:
    image: myapp:latest
    depends_on:
      mysql:
        condition: service_started
    command: ["sh", "-c", "./wait-for-it.sh mysql:3306 -t 60 -- alembic upgrade head"]
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - mynet
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynet
  bot:
    image: myapp:latest
    depends_on:
      init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["sh", "-c", "python src/data_collection_bot/main.py"]
    networks:
      - mynet

networks:
  mynet:
    driver: bridge